### ISSUE TITLE
Text on refresh circle in not centered (vertical-alignment)

### ISSUE THREAD

**Issue by gbraad** [MozillaOnline/HtmlOffice#8]
The text 'refresh' that is shown on the refresh circle (.circle span) is not align in the middle along the vertical axis.

**Comment by gbraad** [comment]
When is the expected time to have a new packaged app released?

**Comment by chardis** [comment]
Hi gbraad, next week we will release new version. Thanks for your help

**Comment by gbraad** [comment]
Fixed
